version: '3'

services:
  php:
    build: ./php
    volumes:
      - ./html:/var/www/html
    ports:
      - 80:80
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_HOST=mysql
  #     - PMA_USER=root
  #     - PMA_PASSWORD=my-secret-pw
  #   links:
  #     - mysql
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./phpmyadmin/sessions:/sessions