version: '3'

services:
  php:
    build: ./php
    volumes:
      - ./html:/var/www/html
    ports:
      - 80:80
  mysql:
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw